metadata:
  annotations:
    api.service.kubernetes.io/path: /
spec:
  type: |
    {{ .Values.name . }}
  selector:
    app: spring-boot-docker
  ports:
    - port: 8080
      targetport: 8080
      nodePort: 32000

