---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: spd
  namespace: ${k8s_namespace}
spec:
  chart:
    spec:
      version: ">=1.0.0 <1.0.8"
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ${hr_name}
  namespace: ${flux_namespace}
spec:
  interval: 10m0s
  timeout: 1m0s
  url: https://chandanbsc.github.io/spring-boot-dochelm
